### 1	Create a 1D NumPy array of numbers from 0 to 9.	


In [39]:
import numpy as np
lst=[0,1,2,3,4,5,6,7,8,9]
a1=np.array(lst)
lst


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 2 Create a 2D array of shape (3, 3) with all elements as 1.	


In [40]:
arr1=np.ones([3,3],dtype=np.int64,order='c')
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

### 3 Generate a NumPy array of 15 random integers between 10 and 50.	


In [41]:
arr=np.array([12,34,54,21,32,43,54,61,28,45,46,30,50,10,49])
arr

array([12, 34, 54, 21, 32, 43, 54, 61, 28, 45, 46, 30, 50, 10, 49])

### 4 Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive).	


In [54]:

evenly_spaced_array=np.linspace(0,1,5)
print(evenly_spaced_array)


[0.   0.25 0.5  0.75 1.  ]


### 5 Create a 4x4 identity matrix using NumPy.	


In [51]:
a1=np.eye(4)
a1


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6 Create an array from the list [10, 20, 30, 40] and change the data type to float.	


In [44]:
l=[10,20,30,40]
ar=np.array(l,dtype=np.float64)
ar

array([10., 20., 30., 40.])

 ### 7 Create a 3x3 array with values from 1 to 9, then extract the second column.	


In [45]:
a1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a1[3:3]

array([], shape=(0, 3), dtype=int32)

### 8 Create a 1D array with 10 elements and reshape it into a 2x5 matrix.	


In [46]:
a1=np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 9 Create two 2x2 matrices and perform matrix multiplication.	


In [47]:
ary=np.array([1,2,3,4]).reshape(2,2)
ary
ary1=np.array([5,6,7,8]).reshape(2,2)
ary1
np.multiply(ary,ary1)

array([[ 5, 12],
       [21, 32]])

### 10 Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100.	


In [48]:
arr = np.array([5, 12, 7, 18, 3])
arr[arr>10]=100
arr

array([  5, 100,   7, 100,   3])